const pool = require('./pool');
//database structure:
/*
tables:   member        |   message
columns:  id -pk        |   id  
          first_name    |   title
          Last_name     |   posted_on
          username      |   content
          password      |   user_id  fk=> member(id)
          member_status |
          is_admin      |

queries:(
        msg:{ 
              addMsg, 
              getAllMessages, 
              deleteMsg(adminPrev true?)
            } ,
    members:{
              addMemeber, 
              activateMembership, 
              getMember, 
              toggleAdminMod
            }
        )
*/
//messages

//note : id and posted_on are generated by default
//addMsg, 
async function addMsg(userId, message) {
  await pool.query(`
    INSERT INTO
    message (title,          content,          user_id)
    VALUES  ($1,             $2,               $3,     )`,
            [message.title,  message.content,  userId]
  )
}
//getAllMessages, 
//for members only
async function getAllMessagesForMembers() {
  const {rows} = await pool.query(`
    SELECT msg.title, 
           msg.content, 
           msg.posted_on, 
           mbr.username

    FROM message msg
    INNER JOIN member mbr ON msg.user_id = mbr.id
    ORDER BY msg.posted_on DESC
    `)
  return rows;
}
//for guests and users
async function getAllMessagesForNonMembers() {
  const {rows} = await pool.query(`
    SELECT title, 
           content, 
           posted_on, 

    FROM message
    ORDER BY posted_on DESC
    `)
  return rows;
}
//deleteMsg(adminPrev true?)
async function deleteMsg(msgId) {
  await pool.query(`
    DELETE FROM message
    WHERE id = $1
    `, [msgId])
}

//members:
//note: id is generated, member_status and is_admin are false by default

//addMemeber: takes full user object as an argument
async function addMember(user) {
  await pool.query(`
    INSERT INTO 
    member (first_name,     last_name,     username,      password) 
    VALUES ($1,             $2,            $3,            $4)`, 
           [user.firstName, user.lastName, user.username, user.password]);
};
//activateMembership: takes user.id as an argument
async function activateMembership(id) {
  await pool.query(`
    UPDATE member
    SET member_status = true
    WHERE id = $1
    `,[id]);
};
//getMember: takes user.username as an argument
async function getMember(username) {
  const {rows} = await pool.query(`      
  SELECT * FROM member 
  WHERE username = $1
    `,[username]);
  return rows[0];
  
};
async function getMemberById(id) {
  const {rows} = await pool.query(`      
  SELECT * FROM member 
  WHERE id = $1
    `,[id]);
  return rows[0];
  
};
//toggleAdminMod: takes user.id as an argument
async function toggleAdminMod(id) {
  await pool.query(`
    UPDATE member
    SET is_admin = NOT is_admin
    WHERE id = $1
    `,[id]);
};

module.exports = {
  //message actions. 
  addMsg, 
  getAllMessagesForMembers, 
  getAllMessagesForNonMembers,
  deleteMsg,
  //member actions
  addMember,
  activateMembership,
  getMember,
  getMemberById,
  toggleAdminMod,

};